### PR TITLE
fix: toggle button background in light mode

### PR DESCRIPTION
**Pull request by CYBWEBALI**
### PR

Issue Number: #30 

Fixed background color to green in light mode of toggle button.

### CODE REVIEW

**Comment by PriyansuMaurya** [comment]
Current:

image

Your changes:

image

If you look closely, your changes do not seem consistent with the overall UI.

I have checked all the available options.

image

But I think old one is very consistent with the UI. So, I would say go with the old one

image

**Comment by Ameya02** [comment]
@CYBWEBALI  please make the changes given by @PriyansuMaurya and update the PR

**Comment by CYBWEBALI** [comment]
Hence there are no changes you can close this pr

**Comment by rajkaranm** [comment]
Hey Thanks for contribution but this issue can be solved by just adding 

`className="text-[color:var(--primary-color)]"`

To Navbar component in line 22, this line add class of color to --primary-color which green by tailwind. Hope you understood and just change color don't change fontSize of the icon.

**Comment by CYBWEBALI** [comment]
> Hey Thanks for contribution but this issue can be solved by just adding
> 
> `className="text-[color:var(--primary-color)]"`
> 
> To Navbar component in line 22, this line add class of color to --primary-color which green by tailwind. Hope you understood and just change color don't change fontSize of the icon.

Current Output after adding this line:
image

Expected Ouput:
image

**Comment by PriyansuMaurya** [comment]
> Hence, there are no changes. You can close this PR.

The main motto of the #30 was to add a **green background color in light mode**, but you diverted from the main point of the issue. Just do the changes as per the issue, nothing more.

Here, I present you with two options:

OPTION - 1
```
<BsToggleOn size={30} />
            ) : (
<BsToggleOff size={30} color="#22C55E"/>
```

OPTION - 2

```
<BsToggleOn size={30} />
            ) : (
<BsToggleOff size={30} className="bg-[color:var(--primary-color)]"/>
```

Try both of them, and whichever works fine based on that generate the pull request.

**Comment by CYBWEBALI** [comment]
I just did a small fix,I just rotated the BsToggleOn and I have achieved what we wanted.
image

**Comment by PriyansuMaurya** [comment]
Great! Create a new PR.

**Comment by CYBWEBALI** [comment]
Updated This PR Only.
Kindly Check the Code.

**Review by PriyansuMaurya — APPROVED** [review]

**Review by Ameya02 — APPROVED** [review]
LTGM

**Comment by PriyansuMaurya** [comment]
You nailed this pull request! Keep up the good work.

**Pull request merged**
